<template>
  <div
    class="items container flex flex-wrap justify-center sm:justify-between mx-auto"
    data-aos="fade-down"
  >
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="1500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2000"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2700"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="1500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2000"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2700"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="1500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2000"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2500"
    />
    <BaseCard
      class="2xl:w-3/12"
      data-aos="fade-down"
      data-aos-duration="2700"
    />
  </div>
</template>

<script>
export default {}
</script>

<style></style>
